<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>Wpf_Pharmacy</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\Cache\10.jpeg" />
    <None Remove="Data\Cache\100.jpeg" />
    <None Remove="Data\Cache\101.jpeg" />
    <None Remove="Data\Cache\102.jpeg" />
    <None Remove="Data\Cache\103.jpeg" />
    <None Remove="Data\Cache\104.jpeg" />
    <None Remove="Data\Cache\105.jpeg" />
    <None Remove="Data\Cache\106.jpeg" />
    <None Remove="Data\Cache\107.jpeg" />
    <None Remove="Data\Cache\108.jpeg" />
    <None Remove="Data\Cache\109.jpeg" />
    <None Remove="Data\Cache\11.jpeg" />
    <None Remove="Data\Cache\110.jpeg" />
    <None Remove="Data\Cache\111.jpeg" />
    <None Remove="Data\Cache\112.jpeg" />
    <None Remove="Data\Cache\113.jpeg" />
    <None Remove="Data\Cache\114.jpeg" />
    <None Remove="Data\Cache\115.jpeg" />
    <None Remove="Data\Cache\116.jpeg" />
    <None Remove="Data\Cache\117.jpeg" />
    <None Remove="Data\Cache\118.jpeg" />
    <None Remove="Data\Cache\119.jpeg" />
    <None Remove="Data\Cache\12.png" />
    <None Remove="Data\Cache\120.jpeg" />
    <None Remove="Data\Cache\121.jpeg" />
    <None Remove="Data\Cache\122.jpeg" />
    <None Remove="Data\Cache\123.jpeg" />
    <None Remove="Data\Cache\124.jpeg" />
    <None Remove="Data\Cache\125.jpeg" />
    <None Remove="Data\Cache\126.jpeg" />
    <None Remove="Data\Cache\127.jpeg" />
    <None Remove="Data\Cache\128.jpeg" />
    <None Remove="Data\Cache\129.jpeg" />
    <None Remove="Data\Cache\13.png" />
    <None Remove="Data\Cache\130.jpeg" />
    <None Remove="Data\Cache\131.jpeg" />
    <None Remove="Data\Cache\132.jpeg" />
    <None Remove="Data\Cache\133.jpeg" />
    <None Remove="Data\Cache\134.jpeg" />
    <None Remove="Data\Cache\135.jpeg" />
    <None Remove="Data\Cache\136.jpeg" />
    <None Remove="Data\Cache\137.jpeg" />
    <None Remove="Data\Cache\138.jpeg" />
    <None Remove="Data\Cache\139.jpeg" />
    <None Remove="Data\Cache\14.jpeg" />
    <None Remove="Data\Cache\140.jpeg" />
    <None Remove="Data\Cache\141.jpeg" />
    <None Remove="Data\Cache\142.jpeg" />
    <None Remove="Data\Cache\143.jpeg" />
    <None Remove="Data\Cache\144.jpeg" />
    <None Remove="Data\Cache\145.jpeg" />
    <None Remove="Data\Cache\146.jpeg" />
    <None Remove="Data\Cache\147.jpeg" />
    <None Remove="Data\Cache\148.jpeg" />
    <None Remove="Data\Cache\149.jpeg" />
    <None Remove="Data\Cache\15.png" />
    <None Remove="Data\Cache\150.jpeg" />
    <None Remove="Data\Cache\151.png" />
    <None Remove="Data\Cache\152.png" />
    <None Remove="Data\Cache\153.png" />
    <None Remove="Data\Cache\154.png" />
    <None Remove="Data\Cache\155.png" />
    <None Remove="Data\Cache\156.png" />
    <None Remove="Data\Cache\157.jpeg" />
    <None Remove="Data\Cache\158.jpeg" />
    <None Remove="Data\Cache\159.png" />
    <None Remove="Data\Cache\16.jpeg" />
    <None Remove="Data\Cache\160.jpeg" />
    <None Remove="Data\Cache\161.png" />
    <None Remove="Data\Cache\162.jpeg" />
    <None Remove="Data\Cache\163.jpeg" />
    <None Remove="Data\Cache\164.jpeg" />
    <None Remove="Data\Cache\165.png" />
    <None Remove="Data\Cache\166.jpeg" />
    <None Remove="Data\Cache\167.png" />
    <None Remove="Data\Cache\168.jpeg" />
    <None Remove="Data\Cache\169.jpeg" />
    <None Remove="Data\Cache\17.png" />
    <None Remove="Data\Cache\170.png" />
    <None Remove="Data\Cache\171.jpeg" />
    <None Remove="Data\Cache\172.png" />
    <None Remove="Data\Cache\173.jpeg" />
    <None Remove="Data\Cache\174.jpeg" />
    <None Remove="Data\Cache\175.png" />
    <None Remove="Data\Cache\176.jpeg" />
    <None Remove="Data\Cache\177.png" />
    <None Remove="Data\Cache\178.png" />
    <None Remove="Data\Cache\179.jpeg" />
    <None Remove="Data\Cache\18.jpeg" />
    <None Remove="Data\Cache\180.jpeg" />
    <None Remove="Data\Cache\181.jpeg" />
    <None Remove="Data\Cache\182.jpeg" />
    <None Remove="Data\Cache\183.jpeg" />
    <None Remove="Data\Cache\184.png" />
    <None Remove="Data\Cache\185.png" />
    <None Remove="Data\Cache\186.jpeg" />
    <None Remove="Data\Cache\187.jpeg" />
    <None Remove="Data\Cache\188.jpeg" />
    <None Remove="Data\Cache\189.jpeg" />
    <None Remove="Data\Cache\19.png" />
    <None Remove="Data\Cache\190.png" />
    <None Remove="Data\Cache\191.png" />
    <None Remove="Data\Cache\192.jpeg" />
    <None Remove="Data\Cache\193.png" />
    <None Remove="Data\Cache\194.png" />
    <None Remove="Data\Cache\195.jpeg" />
    <None Remove="Data\Cache\2.png" />
    <None Remove="Data\Cache\20.jpeg" />
    <None Remove="Data\Cache\21.jpeg" />
    <None Remove="Data\Cache\22.jpeg" />
    <None Remove="Data\Cache\23.png" />
    <None Remove="Data\Cache\24.jpeg" />
    <None Remove="Data\Cache\25.jpeg" />
    <None Remove="Data\Cache\26.jpeg" />
    <None Remove="Data\Cache\27.jpeg" />
    <None Remove="Data\Cache\28.jpeg" />
    <None Remove="Data\Cache\29.jpeg" />
    <None Remove="Data\Cache\3.jpeg" />
    <None Remove="Data\Cache\30.jpeg" />
    <None Remove="Data\Cache\31.png" />
    <None Remove="Data\Cache\32.png" />
    <None Remove="Data\Cache\33.jpeg" />
    <None Remove="Data\Cache\34.jpeg" />
    <None Remove="Data\Cache\35.png" />
    <None Remove="Data\Cache\36.png" />
    <None Remove="Data\Cache\37.jpeg" />
    <None Remove="Data\Cache\38.jpeg" />
    <None Remove="Data\Cache\39.png" />
    <None Remove="Data\Cache\4.jpeg" />
    <None Remove="Data\Cache\40.png" />
    <None Remove="Data\Cache\41.png" />
    <None Remove="Data\Cache\42.jpeg" />
    <None Remove="Data\Cache\43.jpeg" />
    <None Remove="Data\Cache\44.png" />
    <None Remove="Data\Cache\45.jpeg" />
    <None Remove="Data\Cache\46.png" />
    <None Remove="Data\Cache\47.jpeg" />
    <None Remove="Data\Cache\48.png" />
    <None Remove="Data\Cache\49.png" />
    <None Remove="Data\Cache\5.png" />
    <None Remove="Data\Cache\50.jpeg" />
    <None Remove="Data\Cache\51.jpeg" />
    <None Remove="Data\Cache\52.png" />
    <None Remove="Data\Cache\53.png" />
    <None Remove="Data\Cache\54.png" />
    <None Remove="Data\Cache\55.png" />
    <None Remove="Data\Cache\56.jpeg" />
    <None Remove="Data\Cache\57.png" />
    <None Remove="Data\Cache\58.jpeg" />
    <None Remove="Data\Cache\59.jpeg" />
    <None Remove="Data\Cache\6.png" />
    <None Remove="Data\Cache\60.png" />
    <None Remove="Data\Cache\61.png" />
    <None Remove="Data\Cache\62.png" />
    <None Remove="Data\Cache\63.jpeg" />
    <None Remove="Data\Cache\64.jpeg" />
    <None Remove="Data\Cache\65.jpeg" />
    <None Remove="Data\Cache\66.jpeg" />
    <None Remove="Data\Cache\67.jpeg" />
    <None Remove="Data\Cache\68.jpeg" />
    <None Remove="Data\Cache\69.jpeg" />
    <None Remove="Data\Cache\7.png" />
    <None Remove="Data\Cache\70.jpeg" />
    <None Remove="Data\Cache\71.jpeg" />
    <None Remove="Data\Cache\72.jpeg" />
    <None Remove="Data\Cache\73.jpeg" />
    <None Remove="Data\Cache\74.jpeg" />
    <None Remove="Data\Cache\75.jpeg" />
    <None Remove="Data\Cache\76.jpeg" />
    <None Remove="Data\Cache\77.jpeg" />
    <None Remove="Data\Cache\78.jpeg" />
    <None Remove="Data\Cache\79.jpeg" />
    <None Remove="Data\Cache\8.jpeg" />
    <None Remove="Data\Cache\80.png" />
    <None Remove="Data\Cache\81.jpeg" />
    <None Remove="Data\Cache\82.jpeg" />
    <None Remove="Data\Cache\83.jpeg" />
    <None Remove="Data\Cache\84.jpeg" />
    <None Remove="Data\Cache\85.jpeg" />
    <None Remove="Data\Cache\86.jpeg" />
    <None Remove="Data\Cache\87.jpeg" />
    <None Remove="Data\Cache\88.jpeg" />
    <None Remove="Data\Cache\89.jpeg" />
    <None Remove="Data\Cache\9.jpeg" />
    <None Remove="Data\Cache\90.jpeg" />
    <None Remove="Data\Cache\91.jpeg" />
    <None Remove="Data\Cache\92.jpeg" />
    <None Remove="Data\Cache\93.jpeg" />
    <None Remove="Data\Cache\94.jpeg" />
    <None Remove="Data\Cache\95.jpeg" />
    <None Remove="Data\Cache\96.jpeg" />
    <None Remove="Data\Cache\97.jpeg" />
    <None Remove="Data\Cache\98.jpeg" />
    <None Remove="Data\Cache\99.jpeg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="FreeSpire.Office" Version="8.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API-Pharmacy\API-Pharmacy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Data\Cache\10.jpeg" />
    <Resource Include="Data\Cache\100.jpeg" />
    <Resource Include="Data\Cache\101.jpeg" />
    <Resource Include="Data\Cache\102.jpeg" />
    <Resource Include="Data\Cache\103.jpeg" />
    <Resource Include="Data\Cache\104.jpeg" />
    <Resource Include="Data\Cache\105.jpeg" />
    <Resource Include="Data\Cache\106.jpeg" />
    <Resource Include="Data\Cache\107.jpeg" />
    <Resource Include="Data\Cache\108.jpeg" />
    <Resource Include="Data\Cache\109.jpeg" />
    <Resource Include="Data\Cache\11.jpeg" />
    <Resource Include="Data\Cache\110.jpeg" />
    <Resource Include="Data\Cache\111.jpeg" />
    <Resource Include="Data\Cache\112.jpeg" />
    <Resource Include="Data\Cache\113.jpeg" />
    <Resource Include="Data\Cache\114.jpeg" />
    <Resource Include="Data\Cache\115.jpeg" />
    <Resource Include="Data\Cache\116.jpeg" />
    <Resource Include="Data\Cache\117.jpeg" />
    <Resource Include="Data\Cache\118.jpeg" />
    <Resource Include="Data\Cache\119.jpeg" />
    <Resource Include="Data\Cache\12.png" />
    <Resource Include="Data\Cache\120.jpeg" />
    <Resource Include="Data\Cache\121.jpeg" />
    <Resource Include="Data\Cache\122.jpeg" />
    <Resource Include="Data\Cache\123.jpeg" />
    <Resource Include="Data\Cache\124.jpeg" />
    <Resource Include="Data\Cache\125.jpeg" />
    <Resource Include="Data\Cache\126.jpeg" />
    <Resource Include="Data\Cache\127.jpeg" />
    <Resource Include="Data\Cache\128.jpeg" />
    <Resource Include="Data\Cache\129.jpeg" />
    <Resource Include="Data\Cache\13.png" />
    <Resource Include="Data\Cache\130.jpeg" />
    <Resource Include="Data\Cache\131.jpeg" />
    <Resource Include="Data\Cache\132.jpeg" />
    <Resource Include="Data\Cache\133.jpeg" />
    <Resource Include="Data\Cache\134.jpeg" />
    <Resource Include="Data\Cache\135.jpeg" />
    <Resource Include="Data\Cache\136.jpeg" />
    <Resource Include="Data\Cache\137.jpeg" />
    <Resource Include="Data\Cache\138.jpeg" />
    <Resource Include="Data\Cache\139.jpeg" />
    <Resource Include="Data\Cache\14.jpeg" />
    <Resource Include="Data\Cache\140.jpeg" />
    <Resource Include="Data\Cache\141.jpeg" />
    <Resource Include="Data\Cache\142.jpeg" />
    <Resource Include="Data\Cache\143.jpeg" />
    <Resource Include="Data\Cache\144.jpeg" />
    <Resource Include="Data\Cache\145.jpeg" />
    <Resource Include="Data\Cache\146.jpeg" />
    <Resource Include="Data\Cache\147.jpeg" />
    <Resource Include="Data\Cache\148.jpeg" />
    <Resource Include="Data\Cache\149.jpeg" />
    <Resource Include="Data\Cache\15.png" />
    <Resource Include="Data\Cache\150.jpeg" />
    <Resource Include="Data\Cache\151.png" />
    <Resource Include="Data\Cache\152.png" />
    <Resource Include="Data\Cache\153.png" />
    <Resource Include="Data\Cache\154.png" />
    <Resource Include="Data\Cache\155.png" />
    <Resource Include="Data\Cache\156.png" />
    <Resource Include="Data\Cache\157.jpeg" />
    <Resource Include="Data\Cache\158.jpeg" />
    <Resource Include="Data\Cache\159.png" />
    <Resource Include="Data\Cache\16.jpeg" />
    <Resource Include="Data\Cache\160.jpeg" />
    <Resource Include="Data\Cache\161.png" />
    <Resource Include="Data\Cache\162.jpeg" />
    <Resource Include="Data\Cache\163.jpeg" />
    <Resource Include="Data\Cache\164.jpeg" />
    <Resource Include="Data\Cache\165.png" />
    <Resource Include="Data\Cache\166.jpeg" />
    <Resource Include="Data\Cache\167.png" />
    <Resource Include="Data\Cache\168.jpeg" />
    <Resource Include="Data\Cache\169.jpeg" />
    <Resource Include="Data\Cache\17.png" />
    <Resource Include="Data\Cache\170.png" />
    <Resource Include="Data\Cache\171.jpeg" />
    <Resource Include="Data\Cache\172.png" />
    <Resource Include="Data\Cache\173.jpeg" />
    <Resource Include="Data\Cache\174.jpeg" />
    <Resource Include="Data\Cache\175.png" />
    <Resource Include="Data\Cache\176.jpeg" />
    <Resource Include="Data\Cache\177.png" />
    <Resource Include="Data\Cache\178.png" />
    <Resource Include="Data\Cache\179.jpeg" />
    <Resource Include="Data\Cache\18.jpeg" />
    <Resource Include="Data\Cache\180.jpeg" />
    <Resource Include="Data\Cache\181.jpeg" />
    <Resource Include="Data\Cache\182.jpeg" />
    <Resource Include="Data\Cache\183.jpeg" />
    <Resource Include="Data\Cache\184.png" />
    <Resource Include="Data\Cache\185.png" />
    <Resource Include="Data\Cache\186.jpeg" />
    <Resource Include="Data\Cache\187.jpeg" />
    <Resource Include="Data\Cache\188.jpeg" />
    <Resource Include="Data\Cache\189.jpeg" />
    <Resource Include="Data\Cache\19.png" />
    <Resource Include="Data\Cache\190.png" />
    <Resource Include="Data\Cache\191.png" />
    <Resource Include="Data\Cache\192.jpeg" />
    <Resource Include="Data\Cache\193.png" />
    <Resource Include="Data\Cache\194.png" />
    <Resource Include="Data\Cache\195.jpeg" />
    <Resource Include="Data\Cache\2.png" />
    <Resource Include="Data\Cache\20.jpeg" />
    <Resource Include="Data\Cache\21.jpeg" />
    <Resource Include="Data\Cache\22.jpeg" />
    <Resource Include="Data\Cache\23.png" />
    <Resource Include="Data\Cache\24.jpeg" />
    <Resource Include="Data\Cache\25.jpeg" />
    <Resource Include="Data\Cache\26.jpeg" />
    <Resource Include="Data\Cache\27.jpeg" />
    <Resource Include="Data\Cache\28.jpeg" />
    <Resource Include="Data\Cache\29.jpeg" />
    <Resource Include="Data\Cache\3.jpeg" />
    <Resource Include="Data\Cache\30.jpeg" />
    <Resource Include="Data\Cache\31.png" />
    <Resource Include="Data\Cache\32.png" />
    <Resource Include="Data\Cache\33.jpeg" />
    <Resource Include="Data\Cache\34.jpeg" />
    <Resource Include="Data\Cache\35.png" />
    <Resource Include="Data\Cache\36.png" />
    <Resource Include="Data\Cache\37.jpeg" />
    <Resource Include="Data\Cache\38.jpeg" />
    <Resource Include="Data\Cache\39.png" />
    <Resource Include="Data\Cache\4.jpeg" />
    <Resource Include="Data\Cache\40.png" />
    <Resource Include="Data\Cache\41.png" />
    <Resource Include="Data\Cache\42.jpeg" />
    <Resource Include="Data\Cache\43.jpeg" />
    <Resource Include="Data\Cache\44.png" />
    <Resource Include="Data\Cache\45.jpeg" />
    <Resource Include="Data\Cache\46.png" />
    <Resource Include="Data\Cache\47.jpeg" />
    <Resource Include="Data\Cache\48.png" />
    <Resource Include="Data\Cache\49.png" />
    <Resource Include="Data\Cache\5.png" />
    <Resource Include="Data\Cache\50.jpeg" />
    <Resource Include="Data\Cache\51.jpeg" />
    <Resource Include="Data\Cache\52.png" />
    <Resource Include="Data\Cache\53.png" />
    <Resource Include="Data\Cache\54.png" />
    <Resource Include="Data\Cache\55.png" />
    <Resource Include="Data\Cache\56.jpeg" />
    <Resource Include="Data\Cache\57.png" />
    <Resource Include="Data\Cache\58.jpeg" />
    <Resource Include="Data\Cache\59.jpeg" />
    <Resource Include="Data\Cache\6.png" />
    <Resource Include="Data\Cache\60.png" />
    <Resource Include="Data\Cache\61.png" />
    <Resource Include="Data\Cache\62.png" />
    <Resource Include="Data\Cache\63.jpeg" />
    <Resource Include="Data\Cache\64.jpeg" />
    <Resource Include="Data\Cache\65.jpeg" />
    <Resource Include="Data\Cache\66.jpeg" />
    <Resource Include="Data\Cache\67.jpeg" />
    <Resource Include="Data\Cache\68.jpeg" />
    <Resource Include="Data\Cache\69.jpeg" />
    <Resource Include="Data\Cache\7.png" />
    <Resource Include="Data\Cache\70.jpeg" />
    <Resource Include="Data\Cache\71.jpeg" />
    <Resource Include="Data\Cache\72.jpeg" />
    <Resource Include="Data\Cache\73.jpeg" />
    <Resource Include="Data\Cache\74.jpeg" />
    <Resource Include="Data\Cache\75.jpeg" />
    <Resource Include="Data\Cache\76.jpeg" />
    <Resource Include="Data\Cache\77.jpeg" />
    <Resource Include="Data\Cache\78.jpeg" />
    <Resource Include="Data\Cache\79.jpeg" />
    <Resource Include="Data\Cache\8.jpeg" />
    <Resource Include="Data\Cache\80.png" />
    <Resource Include="Data\Cache\81.jpeg" />
    <Resource Include="Data\Cache\82.jpeg" />
    <Resource Include="Data\Cache\83.jpeg" />
    <Resource Include="Data\Cache\84.jpeg" />
    <Resource Include="Data\Cache\85.jpeg" />
    <Resource Include="Data\Cache\86.jpeg" />
    <Resource Include="Data\Cache\87.jpeg" />
    <Resource Include="Data\Cache\88.jpeg" />
    <Resource Include="Data\Cache\89.jpeg" />
    <Resource Include="Data\Cache\9.jpeg" />
    <Resource Include="Data\Cache\90.jpeg" />
    <Resource Include="Data\Cache\91.jpeg" />
    <Resource Include="Data\Cache\92.jpeg" />
    <Resource Include="Data\Cache\93.jpeg" />
    <Resource Include="Data\Cache\94.jpeg" />
    <Resource Include="Data\Cache\95.jpeg" />
    <Resource Include="Data\Cache\96.jpeg" />
    <Resource Include="Data\Cache\97.jpeg" />
    <Resource Include="Data\Cache\98.jpeg" />
    <Resource Include="Data\Cache\99.jpeg" />
  </ItemGroup>

</Project>
